export const CATEGORIES = [
  { id: 'general', name: 'General', icon: '🎯' },
  { id: 'animales', name: 'Animales', icon: '🦁' },
  { id: 'comida', name: 'Comida', icon: '🍕' },
  { id: 'deportes', name: 'Deportes', icon: '⚽' },
  { id: 'profesiones', name: 'Profesiones', icon: '👨‍⚕️' },
  { id: 'lugares', name: 'Lugares', icon: '🌍' },
  { id: 'objetos', name: 'Objetos', icon: '📦' },
  { id: 'peliculas', name: 'Películas', icon: '🎬' },
  { id: 'videojuegos', name: 'Videojuegos', icon: '🎮' },
  { id: 'musica', name: 'Música', icon: '🎵' },
  { id: 'transporte', name: 'Transporte', icon: '🛵' },
  { id: 'tecnologia', name: 'Tecnología', icon: '💻' },
  { id: 'sentimientos', name: 'Sentimientos', icon: '💓' },
  { id: 'naturaleza', name: 'Naturaleza', icon: '⛰️' },
  { id: 'colores', name: 'Colores', icon: '🎨' },
  { id: 'superheroes', name: 'Superhéroes', icon: '🦸' },
  { id: 'series', name: 'Series', icon: '📺' },
  { id: 'instrumentos', name: 'Instrumentos', icon: '🎸' },
  { id: 'emociones', name: 'Emociones', icon: '😄' },
  { id: 'ropa', name: 'Ropa', icon: '👕' },
  { id: 'herramientas', name: 'Herramientas', icon: '🛠️' },
  { id: 'ciencia', name: 'Ciencia', icon: '🔬' },
  { id: 'astrología', name: 'Astrología', icon: '♈' },
  { id: 'juguetes', name: 'Juguetes', icon: '🧸' },
  { id: 'electrodomesticos', name: 'Electrodomésticos', icon: '🔌' },
  { id: 'fiestas', name: 'Fiestas', icon: '🎉' },
  { id: 'escuela', name: 'Escuela', icon: '🏫' },
  { id: 'fantasía', name: 'Fantasía', icon: '🧙' },
  { id: 'memes', name: 'Memes', icon: '😂' },
  { id: 'cosas_incomodas', name: 'Cosas Incómodas', icon: '😬' },
  { id: 'actividades_random', name: 'Actividades Random', icon: '🤪' },
  { id: 'palabras_raras', name: 'Palabras Raras', icon: '🤔' },
  { id: 'hogar', name: 'Hogar', icon: '🏠' },
  { id: 'oficina', name: 'Oficina', icon: '🏢' },
  { id: 'clima', name: 'Clima', icon: '🌦️' },
  { id: 'sonidos', name: 'Sonidos', icon: '🔊' },
  { id: 'acciones_graciosas', name: 'Acciones Graciosas', icon: '🤣' },
  { id: 'transporte_ridiculo', name: 'Transporte Ridículo', icon: '🛴' },
  { id: 'cosas_pequenas', name: 'Cosas Pequeñas', icon: '🔍' },
  { id: 'comida_rara', name: 'Comida Rara', icon: '🍳' },
  { id: 'personajes_random', name: 'Personajes Random', icon: '🎭' },
  { id: 'cosas_que_huelen', name: 'Cosas que Huelen', icon: '👃' },
  { id: 'cosas_pegajosas', name: 'Cosas Pegajosas', icon: '🍯' },
  { id: 'cosas_que_asustan', name: 'Cosas que Asustan', icon: '👻' },
  { id: 'cosas_que_no_existen', name: 'Cosas que No Existen', icon: '🦄' },
  { id: 'objetos_sospechosos', name: 'Objetos Sospechosos', icon: '🕵️' },
  { id: 'cosas_que_harias_en_secreto', name: 'Cosas en Secreto', icon: '🤫' },
  { id: 'animales_tontos', name: 'Animales Tontos', icon: '🐔' },
  { id: 'cosas_que_da_pena', name: 'Cosas que Dan Pena', icon: '🙈' },
  { id: 'cosas_que_no_deberian_moverse', name: 'Cosas Inmóviles', icon: '🪑' },
  { id: 'cosas_muy_especificas', name: 'Cosas Muy Específicas', icon: '📌' },
  { id: 'excusas_malas', name: 'Excusas Malas', icon: '🤥' },
  { id: 'acciones_que_parecen_sospechosas', name: 'Acciones Sospechosas', icon: '🧐' },
  { id: 'inventos_raros', name: 'Inventos Raros', icon: '💡' },
  { id: 'cosas_pegajosas_extremas', name: 'Pegajosas Extremas', icon: '🧴' },
  { id: 'cosas_demasiado_silenciosas', name: 'Cosas Silenciosas', icon: '🤐' },
  { id: 'cosas_que_suenan_raro', name: 'Cosas que Suenan Raro', icon: '🔔' },
  { id: 'objetos_magicamente_inutiles', name: 'Objetos Inútiles', icon: '🪄' },
  { id: 'lugares_raros', name: 'Lugares Raros', icon: '🚪' },
  { id: 'cosas_que_nadie_admite', name: 'Cosas que Nadie Admite', icon: '🙊' },
  { id: 'comida_imposible', name: 'Comida Imposible', icon: '🍝' },
  { id: 'cosas_chiquitas_but_poderosas', name: 'Chiquitas pero Poderosas', icon: '⚡' },
]